// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaeiSAzavUnIsAOFOVnmtBfrfe2wED8YI',
    appId: '1:484096318123:web:9acd5392e46de95c7e35ee',
    messagingSenderId: '484096318123',
    projectId: 'registertest-84edd',
    authDomain: 'registertest-84edd.firebaseapp.com',
    storageBucket: 'registertest-84edd.appspot.com',
    measurementId: 'G-MMX8K0DSM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRXP6VW-dVXQuzMizI49tI-lOa7sqesbk',
    appId: '1:484096318123:android:5f0daf5b4596e6b17e35ee',
    messagingSenderId: '484096318123',
    projectId: 'registertest-84edd',
    storageBucket: 'registertest-84edd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeTbLC74itmRtdCn4rZVgHi3rCaXASDkk',
    appId: '1:484096318123:ios:df6465374d8cbc757e35ee',
    messagingSenderId: '484096318123',
    projectId: 'registertest-84edd',
    storageBucket: 'registertest-84edd.appspot.com',
    iosBundleId: 'com.example.registerr2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeTbLC74itmRtdCn4rZVgHi3rCaXASDkk',
    appId: '1:484096318123:ios:1e505f34b192c81b7e35ee',
    messagingSenderId: '484096318123',
    projectId: 'registertest-84edd',
    storageBucket: 'registertest-84edd.appspot.com',
    iosBundleId: 'com.example.registerr2.RunnerTests',
  );
}
